//varie macro di utilizzo generale, come i percorsi per i vari file

/* macro delle librerie, accessibili solo da file in una cartella diversa dalla libreria,
 * e di un livello superiore*/ 
#define PROCESS_H "../processo/process.h"
#define SETTING_H "../setting/setting.h"
#define UTILITY_H "../utility/utility.h"
#define PROCESS_LIST_H "../lista_processo/process_list.h"
#define STAT_H "../statistics/stat.h"

/* macro per le varie politiche di scheduling */
#define FCFS_H "../FCFS/fcfs.h"
#define RR_H "../RR/rr.h"
#define SJF_H "../SJF/sjf.h"
#define SRJF_H "../SRJF/srjf.h"

/* macro per i file di setting */
#define SET_TEST "../setting/setting.txt"
#define SET_1 "../file/setting/set1.txt"
#define SET_2 "../file/setting/set2.txt"
#define SET_3 "../file/setting/set3.txt"
#define SET_4 "../file/setting/set4.txt"
#define SET_5 "../file/setting/set5.txt"
#define SET_6 "../file/setting/set6.txt"
#define SET_7 "../file/setting/set7.txt"
#define SET_8 "../file/setting/set8.txt"
#define SET_9 "../file/setting/set9.txt"
#define SET_10 "../file/setting/set10.txt"
#define SET_11 "../file/setting/set11.txt"
#define SET_12 "../file/setting/set12.txt"
#define SET_13 "../file/setting/set13.txt"
#define SET_14 "../file/setting/set14.txt"
#define SET_15 "../file/setting/set15.txt"
#define SET_16 "../file/setting/set16.txt"
#define SET_17 "../file/setting/set17.txt"
#define SET_18 "../file/setting/set18.txt"
#define SET_19 "../file/setting/set19.txt"
#define SET_20 "../file/setting/set20.txt"
#define SET_21 "../file/setting/set21.txt"
#define SET_22 "../file/setting/set22.txt"
#define SET_23 "../file/setting/set23.txt"
#define SET_24 "../file/setting/set24.txt"

/* macro per i file con i risultati */
#define RESULT_TEST "../file/result/result_test.csv"

#define RES_FCFS_1 "../file/result/result_fcfs_set1.txt"
#define RES_FCFS_2 "../file/result/result_fcfs_set2.txt"
#define RES_FCFS_3 "../file/result/result_fcfs_set3.txt"
#define RES_FCFS_4 "../file/result/result_fcfs_set4.txt"
#define RES_FCFS_5 "../file/result/result_fcfs_set5.txt"
#define RES_FCFS_6 "../file/result/result_fcfs_set6.txt"
#define RES_FCFS_7 "../file/result/result_fcfs_set7.txt"
#define RES_FCFS_8 "../file/result/result_fcfs_set8.txt"
#define RES_FCFS_9 "../file/result/result_fcfs_set9.txt"
#define RES_FCFS_10 "../file/result/result_fcfs_set10.txt"
#define RES_FCFS_11 "../file/result/result_fcfs_set11.txt"
#define RES_FCFS_12 "../file/result/result_fcfs_set12.txt"
#define RES_FCFS_13 "../file/result/result_fcfs_set13.txt"
#define RES_FCFS_14 "../file/result/result_fcfs_set14.txt"
#define RES_FCFS_15 "../file/result/result_fcfs_set15.txt"
#define RES_FCFS_16 "../file/result/result_fcfs_set16.txt"
#define RES_FCFS_17 "../file/result/result_fcfs_set17.txt"
#define RES_FCFS_18 "../file/result/result_fcfs_set18.txt"
#define RES_FCFS_19 "../file/result/result_fcfs_set19.txt"
#define RES_FCFS_20 "../file/result/result_fcfs_set20.txt"
#define RES_FCFS_21 "../file/result/result_fcfs_set21.txt"
#define RES_FCFS_22 "../file/result/result_fcfs_set22.txt"
#define RES_FCFS_23 "../file/result/result_fcfs_set23.txt"
#define RES_FCFS_24 "../file/result/result_fcfs_set24.txt"
#define FCFS_FINAL_RES "../file/result/result_fcfs.csv"

#define RES_RR_1 "../file/result/result_rr_set1.txt"
#define RES_RR_2 "../file/result/result_rr_set2.txt"
#define RES_RR_3 "../file/result/result_rr_set3.txt"
#define RES_RR_4 "../file/result/result_rr_set4.txt"
#define RES_RR_5 "../file/result/result_rr_set5.txt"
#define RES_RR_6 "../file/result/result_rr_set6.txt"
#define RES_RR_7 "../file/result/result_rr_set7.txt"
#define RES_RR_8 "../file/result/result_rr_set8.txt"
#define RES_RR_9 "../file/result/result_rr_set9.txt"
#define RES_RR_10 "../file/result/result_rr_set10.txt"
#define RES_RR_11 "../file/result/result_rr_set11.txt"
#define RES_RR_12 "../file/result/result_rr_set12.txt"
#define RES_RR_13 "../file/result/result_rr_set13.txt"
#define RES_RR_14 "../file/result/result_rr_set14.txt"
#define RES_RR_15 "../file/result/result_rr_set15.txt"
#define RES_RR_16 "../file/result/result_rr_set16.txt"
#define RES_RR_17 "../file/result/result_rr_set17.txt"
#define RES_RR_18 "../file/result/result_rr_set18.txt"
#define RES_RR_19 "../file/result/result_rr_set19.txt"
#define RES_RR_20 "../file/result/result_rr_set20.txt"
#define RES_RR_21 "../file/result/result_rr_set21.txt"
#define RES_RR_22 "../file/result/result_rr_set22.txt"
#define RES_RR_23 "../file/result/result_rr_set23.txt"
#define RES_RR_24 "../file/result/result_rr_set24.txt"
#define RR_FINAL_RES "../file/result/result_rr.csv"

#define RES_SJF_1 "../file/result/result_sjf_set1.txt"
#define RES_SJF_2 "../file/result/result_sjf_set2.txt"
#define RES_SJF_3 "../file/result/result_sjf_set3.txt"
#define RES_SJF_4 "../file/result/result_sjf_set4.txt"
#define RES_SJF_5 "../file/result/result_sjf_set5.txt"
#define RES_SJF_6 "../file/result/result_sjf_set6.txt"
#define RES_SJF_7 "../file/result/result_sjf_set7.txt"
#define RES_SJF_8 "../file/result/result_sjf_set8.txt"
#define RES_SJF_9 "../file/result/result_sjf_set9.txt"
#define RES_SJF_10 "../file/result/result_sjf_set10.txt"
#define RES_SJF_11 "../file/result/result_sjf_set11.txt"
#define RES_SJF_12 "../file/result/result_sjf_set12.txt"
#define RES_SJF_13 "../file/result/result_sjf_set13.txt"
#define RES_SJF_14 "../file/result/result_sjf_set14.txt"
#define RES_SJF_15 "../file/result/result_sjf_set15.txt"
#define RES_SJF_16 "../file/result/result_sjf_set16.txt"
#define RES_SJF_17 "../file/result/result_sjf_set17.txt"
#define RES_SJF_18 "../file/result/result_sjf_set18.txt"
#define RES_SJF_19 "../file/result/result_sjf_set19.txt"
#define RES_SJF_20 "../file/result/result_sjf_set20.txt"
#define RES_SJF_21 "../file/result/result_sjf_set21.txt"
#define RES_SJF_22 "../file/result/result_sjf_set22.txt"
#define RES_SJF_23 "../file/result/result_sjf_set23.txt"
#define RES_SJF_24 "../file/result/result_sjf_set24.txt"
#define SJF_FINAL_RES "../file/result/result_sjf.csv" 

#define RES_SRJF_1 "../file/result/result_srjf_set1.txt"
#define RES_SRJF_2 "../file/result/result_srjf_set2.txt"
#define RES_SRJF_3 "../file/result/result_srjf_set3.txt"
#define RES_SRJF_4 "../file/result/result_srjf_set4.txt"
#define RES_SRJF_5 "../file/result/result_srjf_set5.txt"
#define RES_SRJF_6 "../file/result/result_srjf_set6.txt"
#define RES_SRJF_7 "../file/result/result_srjf_set7.txt"
#define RES_SRJF_8 "../file/result/result_srjf_set8.txt"
#define RES_SRJF_9 "../file/result/result_srjf_set9.txt"
#define RES_SRJF_10 "../file/result/result_srjf_set10.txt"
#define RES_SRJF_11 "../file/result/result_srjf_set11.txt"
#define RES_SRJF_12 "../file/result/result_srjf_set12.txt"
#define RES_SRJF_13 "../file/result/result_srjf_set13.txt"
#define RES_SRJF_14 "../file/result/result_srjf_set14.txt"
#define RES_SRJF_15 "../file/result/result_srjf_set15.txt"
#define RES_SRJF_16 "../file/result/result_srjf_set16.txt"
#define RES_SRJF_17 "../file/result/result_srjf_set17.txt"
#define RES_SRJF_18 "../file/result/result_srjf_set18.txt"
#define RES_SRJF_19 "../file/result/result_srjf_set19.txt"
#define RES_SRJF_20 "../file/result/result_srjf_set20.txt"
#define RES_SRJF_21 "../file/result/result_srjf_set21.txt"
#define RES_SRJF_22 "../file/result/result_srjf_set22.txt"
#define RES_SRJF_23 "../file/result/result_srjf_set23.txt"
#define RES_SRJF_24 "../file/result/result_srjf_set24.txt"
#define SRJF_FINAL_RES "../file/result/result_srjf.csv"

/* macro numeriche */
#define NUM_CICLI 10
#define QUANTUM 5
#define NUM_SET 24
